# Generated by Django 4.1.1 on 2022-10-08 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imdbid', models.TextField()),
                ('imageurl', models.URLField()),
                ('watched', models.BooleanField(default=False)),
                ('url', models.URLField(default='https://www.imdb.com/title/<built-in function id>')),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
