# Generated by Django 4.1.1 on 2022-10-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flist', '0002_user_movies_movie'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('user', 'imdbid'), name='unique_movie'),
        ),
    ]
