# Generated by Django 4.1.1 on 2022-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flist', '0003_movie_unique_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(default='https://www.imdb.com/title/<django.db.models.fields.TextField>'),
        ),
    ]
