# Generated by Django 4.1.1 on 2022-11-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flist', '0004_alter_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
