# Generated by Django 4.1.1 on 2022-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flist', '0005_alter_movie_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(),
        ),
    ]
